stages:
  prepare_data:
    cmd: python src/data/prepare_data.py
    deps:
    - src/data/prepare_data.py
    - src/data/bigquery_client.py
    outs:
    - data/processed/train.csv
    - data/processed/val.csv
    - data/processed/test.csv
    - data/processed/feature_info.json

  feature_engineering:
    cmd: python src/features/build_features.py
    deps:
    - data/processed/
    - src/features/build_features.py
    outs:
    - data/interim/features.pkl

  train:
    cmd: python src/models/train_model.py --config experiments/configs/config.yaml
    deps:
    - data/interim/features.pkl
    - src/models/train_model.py
    - experiments/configs/config.yaml
    outs:
    - models/saved/model.pkl
    metrics:
    - experiments/outputs/metrics.json
    plots:
    - experiments/outputs/plots/confusion_matrix.png
    - experiments/outputs/plots/feature_importance.png

  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
    - models/saved/model.pkl
    - data/processed/test.csv
    - src/models/evaluate_model.py
    outs:
    - experiments/outputs/evaluation_results.json